# Generated by Django 3.1.2 on 2021-01-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210114_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='course_code',
            field=models.ManyToManyField(to='login.course'),
        ),
        migrations.AddField(
            model_name='students',
            name='credit_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='review',
            field=models.CharField(default='', max_length=700),
        ),
    ]
