# Generated by Django 2.2.19 on 2021-02-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210114_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='students',
            name='course_code',
        ),
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
