# Generated by Django 2.2.19 on 2021-02-23 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instructor_rate',
            fields=[
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.instructor')),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='department',
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor_bio',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
