# Generated by Django 2.2.19 on 2021-02-23 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rating_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_rate',
            name='instructor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.instructor'),
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.ManyToManyField(null=True, to='dashboard.instructor')),
            ],
        ),
    ]
