# Generated by Django 2.2.19 on 2021-02-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210223_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_desc',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
